# Generated by Django 5.2.7 on 2025-10-10 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(default='zh', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='core.novel')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('novel', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('title_translation', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.volume')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('volume', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_cn', models.CharField(max_length=128)),
                ('term_vi', models.CharField(max_length=128)),
                ('note', models.TextField(blank=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossaries', to='core.novel')),
            ],
            options={
                'unique_together': {('novel', 'term_cn')},
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1)),
                ('content_raw', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True, null=True)),
                ('match_percent', models.FloatField(default=0)),
                ('review', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.chapter')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('chapter', 'index')},
            },
        ),
    ]
