# Generated by Django 5.2.7 on 2025-10-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='match_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(default='imported', max_length=32),
        ),
        migrations.AddField(
            model_name='chapter',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
