# Generated by Django 5.2.7 on 2025-11-02 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chapter_content_raw_chapter_match_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude')], default='gemini', max_length=20)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, help_text='Tên gợi nhớ, VD: Key 1, Key Production', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Số lần sử dụng')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['id'],
            },
        ),
    ]
