# Generated by Django 5.2.6 on 2025-11-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='foreign_char_warning',
            field=models.TextField(blank=True, help_text='Tổng hợp cảnh báo ký tự ngoại ngữ từ tất cả segments', null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='foreign_char_warning',
            field=models.TextField(blank=True, help_text='Cảnh báo ký tự ngoại ngữ trong bản dịch segment này', null=True),
        ),
    ]
