# Generated by Django 5.2.6 on 2025-11-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chapter_foreign_char_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='translation_style',
            field=models.TextField(blank=True, help_text='Hướng dẫn phong cách dịch cho AI (ví dụ: văn phong cổ trang, hiện đại, trẻ trung...)', null=True),
        ),
    ]
